version: '3'

services:
  db:
    image: mysql:latest
    container_name: logistica-db
    environment:
      - MYSQL_ROOT_PASSWORD=p455w0rd
    ports:
      - 3306:3306
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/initdb.sql
    healthcheck:
        test: [ "CMD-SHELL", 'mysql --database=logistica --password=$$MYSQL_ROOT_PASSWORD --execute="SELECT count(*) AS totalTables FROM information_schema.tables WHERE TABLE_SCHEMA=logistica;"' ]
        interval: 30s
        timeout: 20s
        retries: 10

volumes:
  db-data:
  pgadmin-data: